  trigger: none

pool: AgentsPool

steps:

- task: CmdLine@2
  displayName: Install
  inputs:
    script: 'npm install'
    
- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      npm run build