trigger: none

jobs:

# ðŸ”¹ Job 1 â€“ Install
- job: Install
  pool:
    name: AgentsPool
  steps:
  - task: CmdLine@2
    displayName: Npm Install
    inputs:
      script: npm install
  - task: CmdLine@2
    displayName: Npm Build
    inputs:
      script: 'npm run build'

# - job: ManualApproval
#   pool: server
#   dependsOn: Install
#   steps:
#   - task: ManualValidation@1
#     inputs:
#       notifyUsers: 'anujsoam07@gmail.com'
#       instructions: 'Installation check kar lo'
#       onTimeout: 'reject'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
      ArtifactName: 'reactartifacts'
      publishLocation: 'Container'
