trigger: none

pool: AgentsPool

steps:
- task: CmdLine@2
  displayName: Install
  inputs:
    script: |
      apt update
      apt install -y nodejs

- task: CmdLine@2
  displayName: Build
  inputs:
    script: |
      npm install
      npm run build